require "exception_notification/rails"

ExceptionNotification.configure do |config|
  # Ignore additional exception types.
  # ActiveRecord::RecordNotFound, Mongoid::Errors::DocumentNotFound, AbstractController::ActionNotFound and ActionController::RoutingError are already added.
  #
  # Erreurs CLIENT (4xx) provoquées par des bots/scanners : requêtes malformées
  # (ex. Content-Type multipart/form-data avec un corps vide, sondes Next.js
  # "Next-Action"). Rails répond correctement 400 — inutile d'être notifié.
  # Bonus : sans cette ligne, le mail de notif plante lui-même en essayant de
  # lire les params cassés (Rack::Multipart::EmptyContentError re-levée dans le
  # template _request.text.erb).
  config.ignored_exceptions += %w[
    ActionController::BadRequest
    ActionController::InvalidAuthenticityToken
    Rack::Multipart::EmptyContentError
    Rack::QueryParser::InvalidParameterError
  ]

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  # config.ignore_if do |exception, options|
  #   not Rails.env.production?
  # end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w{Googlebot bingbot}

  # Notifiers =================================================================

  # Email notifier sends notifications by email.
  config.add_notifier :email, {
    email_prefix: "[ERROR ON ENSEMBLE PRODUCTION]",
    sender_address: %("Notifier" <no-reply@app-ensemble.com>),
    exception_recipients: %w[bensoucdev@gmail.com]
  }
  config.add_notifier :slack, {
    webhook_url: ENV.fetch("SLACK_NOTIF_WEBHOOK_URL", nil),
    channel: "#ensemble",
    additional_parameters: {
      icon_url: "https://res.cloudinary.com/bensoucdev/image/upload/v1678871863/ensemble/logos/ensemble_icone_umdhbk.png",
      mrkdwn: true
    }
  }
  # Campfire notifier sends notifications to your Campfire room. Requires 'tinder' gem.
  # config.add_notifier :campfire, {
  #   subdomain: 'my_subdomain',
  #   token: 'my_token',
  #   room_name: 'my_room'
  # }

  # HipChat notifier sends notifications to your HipChat room. Requires 'hipchat' gem.
  # config.add_notifier :hipchat, {
  #   api_token: 'my_token',
  #   room_name: 'my_room'
  # }

  # Webhook notifier sends notifications over HTTP protocol. Requires 'httparty' gem.
  # config.add_notifier :webhook, {
  #   url: 'http://example.com:5555/hubot/path',
  #   http_method: :post
  # }
end
