development:
  adapter: solid_cable
  channel_prefix: ensemble_development

test:
  adapter: async
  channel_prefix: your_app_test

production:
  adapter: solid_cable
  channel_prefix: ensemble_production
