development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: your_app_development

test:
  adapter: async
  channel_prefix: your_app_test

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: your_app_production
