default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: ["default", "mailers"]
      threads: 3
      polling_interval: 1
      concurrency: 5

development:
  <<: *default

test:
  <<: *default
