s = Skill.where(grade: "CM2")
c = s.count
puts "Destroy all CM2 Workplan"
wp = WorkPlan.where(grade: "CM2")
wp.each(&:destroy)
puts "Destroy all CM2 skills & challenges"
s.each { |skill|
  chals = Challenge.where(skill: skill)
  chals.each(&:destroy)
  skill.destroy
}

puts "#{c} skills ont été détruites"

puts "creating all the Skills"

Skill.create!(domain: "Calcul", level: "1", symbol: "", name: "Additionner un nombre à deux chiffres et un nombre à un chiffre", grade: "CM2")
Skill.create!(domain: "Calcul", level: "1", symbol: "", name: "Connaître les tables d’addition", grade: "CM2")
Skill.create!(domain: "Calcul", level: "1", symbol: "", name: "Additionner des multiples de 10 entre eux", grade: "CM2")
Skill.create!(domain: "Calcul", level: "1", symbol: "", name: "Connaître les doubles et moitiés des nombres jusqu’à 10", grade: "CM2")
Skill.create!(domain: "Calcul", level: "1", symbol: "", name: "Écrire des nombres dictés jusqu’à 1 000", grade: "CM2")
Skill.create!(domain: "Calcul", level: "2", symbol: "", name: "Connaître le complément à 100 d’un nombre", grade: "CM2")
Skill.create!(domain: "Calcul", level: "2", symbol: "", name: "Réaliser des soustractions sur les 20 premiers nombres", grade: "CM2")
Skill.create!(domain: "Calcul", level: "2", symbol: "", name: "Connaître les tables de multiplication par 2, 5 et 10", grade: "CM2")
Skill.create!(domain: "Calcul", level: "2", symbol: "", name: "Savoir si un nombre est multiple de 2, 5 ou 10", grade: "CM2")
Skill.create!(domain: "Calcul", level: "2", symbol: "", name: "Écrire des nombres dictés jusqu’à 10 000", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Connaître le complément à 1 000 d’un nombre", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Ajouter , retirer 9,99 …1, 11 à un nombre", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Réaliser des additions et des soustractions sur les 100 premiers nombres", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Connaître les tables de multiplication jusqu’à × 5", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Multiplier un nombre par 10,100, 1 000 …", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Savoir si un nombre est multiple de 2, 3, 4, 5 ou 10", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Connaître les doubles et moitiés des nombres jusqu’à 100", grade: "CM2")
Skill.create!(domain: "Calcul", level: "3", symbol: "", name: "Écrire des nombres dictés jusqu’à 100 000", grade: "CM2")
Skill.create!(domain: "Calcul", level: "4", symbol: "", name: "Connaître les tables de multiplication jusqu’à × 10", grade: "CM2")
Skill.create!(domain: "Calcul", level: "4", symbol: "", name: "Réaliser des soustractions sur les 1 000 premiers nombres", grade: "CM2")
Skill.create!(domain: "Calcul", level: "4", symbol: "", name: "Connaître le complément d’un décimal à l’entier supérieur", grade: "CM2")
Skill.create!(domain: "Calcul", level: "4", symbol: "", name: "Estimer des sommes, des différences", grade: "CM2")
Skill.create!(domain: "Calcul", level: "4", symbol: "", name: "Encadrer un nombre entier à la dizaine, à la centaine", grade: "CM2")
Skill.create!(domain: "Calcul", level: "4", symbol: "", name: "Écrire des nombres dictés jusqu’à 1 000 000", grade: "CM2")
Skill.create!(domain: "Calcul", level: "5", symbol: "", name: "Ajouter, retirer 19, 29, 99, 101", grade: "CM2")
Skill.create!(domain: "Calcul", level: "5", symbol: "", name: "Savoir diviser un nombre par 2, par 5, par 10", grade: "CM2")
Skill.create!(domain: "Calcul", level: "5", symbol: "", name: "Additionner ou soustraire heures, minutes et secondes", grade: "CM2")
Skill.create!(domain: "Calcul", level: "5", symbol: "", name: "Connaître les doubles et moitiés des nombres jusqu’à 500", grade: "CM2")
Skill.create!(domain: "Calcul", level: "5", symbol: "", name: "Écrire tout nombre entier dicté ", grade: "CM2")
Skill.create!(domain: "Calcul", level: "6", symbol: "", name: "Multiplier par 11 –20 – 50 – 99 –100 –101– 999 –1 000 –1 001", grade: "CM2")
Skill.create!(domain: "Calcul", level: "6", symbol: "", name: "Diviser un nombre par 10 – 20 – 100 – 200 – 1 000 – 2 000", grade: "CM2")
Skill.create!(domain: "Calcul", level: "6", symbol: "", name: "Additionner ou soustraire des décimaux", grade: "CM2")
Skill.create!(domain: "Calcul", level: "6", symbol: "", name: "Encadrer un décimal par des entiers, des dizaines entières", grade: "CM2")
Skill.create!(domain: "Calcul", level: "6", symbol: "", name: "Écrire des nombres décimaux dictés", grade: "CM2")
Skill.create!(domain: "Calcul", level: "7", symbol: "", name: "Réaliser des additions, des multiplications et des soustractions sur tous les nombres (y compris décimaux)", grade: "CM2")
Skill.create!(domain: "Calcul", level: "7", symbol: "", name: "Multiplier par 0,5 – 0,25", grade: "CM2")
Skill.create!(domain: "Calcul", level: "7", symbol: "", name: "Diviser un nombre décimal par 2, par 3 et par 5", grade: "CM2")
Skill.create!(domain: "Calcul", level: "7", symbol: "", name: "Réaliser des calculs avec des pourcentages", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "1", symbol: "", name: "Se repérer sur un quadrillage", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "1", symbol: "", name: "Reconnaitre le carré, le rectangle, le triangle", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "1", symbol: "", name: "Reconnaitre les polygones", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "1", symbol: "", name: "Distinguer les droites et les segments", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "1", symbol: "", name: "Savoir tracer les droites et les segments", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "1", symbol: "", name: "Trouver le milieu d’un segment", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "1", symbol: "", name: "Se repérer, décrire ou exécuter des déplacements sur un plan", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "2", symbol: "", name: "Comparer des angles", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "2", symbol: "", name: "Reconnaitre les angles droits; utiliser l’ équerre", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "2", symbol: "", name: "Reconnaitre les droites perpendiculaires", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "2", symbol: "", name: "Tracer des droites perpendiculaires", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "2", symbol: "", name: "Tracer un carré", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "2", symbol: "", name: "Tracer un rectangle", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "2", symbol: "", name: "Tracer un cercle en utilisant le vocabulaire rayon , diamètre", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "3", symbol: "", name: "Reconnaitre les droites parallèles", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "3", symbol: "", name: "Tracer des droites parallèles", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "3", symbol: "", name: "Connaitre les triangles particuliers (rectangle, isocèle, équilatéral)", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "3", symbol: "", name: "Réaliser des symétries sur quadrillage", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "3", symbol: "", name: "Comparer des angles dans une figure", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "3", symbol: "", name: "Terminer les tracés d’un carré", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "3", symbol: "", name: "Terminer les tracés  d’un rectangle", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "4", symbol: "", name: "Reconnaitre les solides courants", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "4", symbol: "", name: "Connaitre le vocabulaire associé aux solides", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "4", symbol: "", name: "Construire un triangle dont la longueur des côtés est donnée", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "4", symbol: "", name: "Associer une figure à son portrait", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "4", symbol: "", name: "Repérer, décrire ou exécuter des déplacements sur une carte", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "4", symbol: "", name: "Rechercher des axes de symétrie dans une figure", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "5", symbol: "", name: "Associer un solide et son patron", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "5", symbol: "", name: "Réaliser le patron d’un cube", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "5", symbol: "", name: "Réaliser le patron d’un pavé droit", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "5", symbol: "", name: "Tracer un triangle particulier", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "5", symbol: "", name: "Réaliser des tracés de symétrie axiale (plus complexes)", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "5", symbol: "", name: "Suivre le programme de construction d’une figure géométrique", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "5", symbol: "", name: "Reproduire une figure en utilisant les angles", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "6", symbol: "", name: "Réaliser le patron d’autres solides ( pyramide, prisme droit)", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "6", symbol: "", name: "Construire une figure à partir d’un schéma", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "6", symbol: "", name: "Construire une figure à partir d’une description", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "7", symbol: "", name: "Réduire et agrandir des figures", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "7", symbol: "", name: "Rédiger le programme de construction d’une figure géométrique", grade: "CM2")
Skill.create!(domain: "Géométrie", level: "7", symbol: "", name: "Connaitre les quadrilatères (dont losanges et  parallélogrammes)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "1", symbol: "", name: "Se repérer dans un calendrier", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "1", symbol: "", name: "Lire l’heure (heure « pile », quart, demie)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "1", symbol: "", name: "Estimer des mesures (g, kg ou mm, m, km…)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "1", symbol: "", name: "Mesurer des longueurs (cm et mm)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "1", symbol: "", name: "Tracer des longueurs (cm et mm)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "1", symbol: "", name: "Mesurer des lignes brisées (cm et mm)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "2", symbol: "", name: "Connaitre les relations entre les unités de longueur (m, dm, cm, mm)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "2", symbol: "", name: "Tracer des longueurs (m, dm, cm, mm)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "2", symbol: "", name: "Calculer des lignes brisées (cm et mm)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "2", symbol: "", name: "Mesurer le périmètre d’un polygone", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "2", symbol: "", name: "Lire l’heure (multiples de 5)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "2", symbol: "", name: "Réaliser des calculs sur la monnaie (euros et centimes )", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "3", symbol: "", name: "Calculer des distances (m, dam, hm, km)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "3", symbol: "", name: "Connaitre les relations entre les unités de distance (m,dam, hm, km)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "3", symbol: "", name: "Connaitre les relations entre les unités de  contenances", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "3", symbol: "", name: "Connaitre les relations entre les unités de masse", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "3", symbol: "", name: "Calculer le périmètre d’une figure", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "3", symbol: "", name: "Lire l’heure (minute)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "4", symbol: "", name: "Comparer des surfaces selon leur aire", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "4", symbol: "", name: "Construire des surfaces de même aire", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "4", symbol: "", name: "Mesurer des aires avec une unité donnée", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "4", symbol: "", name: "Lire l’heure (seconde)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "5", symbol: "", name: "Mesurer un aire (carré et rectangle)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "5", symbol: "", name: "Calculer une aire (carré, rectangle)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "5", symbol: "", name: "Résoudre des problèmes avec des masses", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "5", symbol: "", name: "Résoudre des problèmes avec des contenances", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "5", symbol: "", name: "Résoudre des problèmes avec des durées", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "5", symbol: "", name: "Résoudre des problèmes avec des longueurs et des distances", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "6", symbol: "", name: "Différencier périmètres et aires", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "6", symbol: "", name: "Mesurer et calculer des mesures avec des décimaux", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "6", symbol: "", name: "Associer écriture décimale et écriture complexe d’une mesure", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "6", symbol: "", name: "Calculer avec des mesures décimales", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "6", symbol: "", name: "Comparer et qualifier des angles (droit, aigu, obtus)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "7", symbol: "", name: "Comparer des volumes", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "7", symbol: "", name: "Mesurer et calculer des volumes (pavé droit, cube)", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "7", symbol: "", name: "Formuler l’aire d’un triangle ou d’un disque", grade: "CM2")
Skill.create!(domain: "Grandeurs et Mesures", level: "7", symbol: "", name: "Convertir des unités d’aire", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Lire et écrire les nombres jusqu’à 100", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Décomposer les nombres jusqu’à 100", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Donner la valeur de chaque chiffre d’un nombre jusqu’à 100", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Trouver le « nombre de  » dans un nombre jusqu’à 100", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Comparer et classer les nombres jusqu’à 100", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Repérer et placer les nombres jusqu’à 100 sur une droite graduée", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Connaitre les notions de double et de moitié (demi)", grade: "CM2")
Skill.create!(domain: "Numération", level: "1", symbol: "", name: "Connaitre les nombres pairs et impairs", grade: "CM2")
Skill.create!(domain: "Numération", level: "2", symbol: "", name: "Lire et écrire les nombres jusqu’à 1 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "2", symbol: "", name: "Décomposer les nombres jusqu’à 1 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "2", symbol: "", name: "Donner la valeur de chaque chiffre d’un nombre jusqu’à 1 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "2", symbol: "", name: "Trouver le « nombre de  »dans un nombre jusqu’à 1 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "2", symbol: "", name: "Comparer et classer les nombres jusqu’à 1 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "2", symbol: "", name: "Repérer et placer les nombres jusqu’à 1 000 sur une droite graduée", grade: "CM2")
Skill.create!(domain: "Numération", level: "2", symbol: "", name: "Connaitre les nombres romains jusqu’à XX", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Lire et écrire les nombres jusqu’à 10 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Décomposer les nombres jusqu’à 10 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Donner la valeur de chaque chiffre d’un nombre jusqu’à 10 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Trouver le « nombre de  »dans un nombre jusqu’à 10 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Comparer et classer les nombres jusqu’à 10 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Repérer et placer les nombres jusqu’à 10 000 sur une droite graduée", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Connaitre les nombres romains jusqu’à L", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Connaitre les multiples de 5,10,100 et 1 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "3", symbol: "", name: "Connaitre les notions de triple, de tiers et de quart", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Lire et écrire les nombres jusqu’à 100 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Décomposer les nombres jusqu’à 100 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Donner la valeur de chaque chiffre d’un nombre jusqu’à 100 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Trouver le « nombre de  »dans un nombre jusqu’à 100 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Comparer et classer les nombres jusqu’à 100 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Repérer et placer les nombres jusqu’à 100 000 sur une droite graduée", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Connaitre les nombres romains jusqu’à C", grade: "CM2")
Skill.create!(domain: "Numération", level: "4", symbol: "", name: "Connaitre les multiples de 25,50,250 et 500", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Lire et écrire les nombres jusqu’à 1 000 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Décomposer les nombres jusqu’à 1 000 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Donner la valeur de chaque chiffre d’un nombre jusqu’à 1 000 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Trouver le « nombre de  » dans un nombre jusqu’à 1 000 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Comparer et classer les nombres jusqu’à 1 000 000", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Utiliser des fractions pour mesurer des longueurs", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Construire des segments dont la mesure est donnée par une fraction", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Utiliser des fractions pour mesurer des aires", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Construire une surface dont l’aire est donnée par une fraction", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Associer des fractions à des repères sur une ligne graduée", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Écrire une fraction décimale sous forme d’un nombre décimal", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Comparer des fractions décimales", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Écrire en chiffres un nombre décimal", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Comparer et ranger des nombres décimaux", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Utiliser les relations entre dixièmes, centièmes", grade: "CM2")
Skill.create!(domain: "Numération", level: "5", symbol: "", name: "Décomposer un nombre décimal", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Lire et écrire les grands nombres", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Décomposer les grands nombres", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Comparer et classer les grands nombres", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Encadrer des nombres entiers à la dizaine, à la centaine…", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Décomposer une fraction (partie entière)", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Trouver la fraction égale à la somme d’un entier et d’une fraction", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Comparer des fractions", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Encadrer une fraction par deux nombres entiers", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Passer d’une écriture décimale à une écriture fractionnaire", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Associer des décimaux à des repères sur une ligne graduée", grade: "CM2")
Skill.create!(domain: "Numération", level: "6", symbol: "", name: "Encadrer et intercaler des décimaux entre deux autres  décimaux", grade: "CM2")
Skill.create!(domain: "Numération", level: "7", symbol: "", name: "Utiliser les décimaux pour rendre compte des mesures de grandeurs", grade: "CM2")
Skill.create!(domain: "Numération", level: "7", symbol: "", name: "Trouver l’arrondi d’un nombre à l’unité, à la dizaine ou au dixième près", grade: "CM2")
Skill.create!(domain: "Numération", level: "7", symbol: "", name: "Écrire un nombre décimal d’usage courant sous forme d’une fraction", grade: "CM2")
Skill.create!(domain: "Numération", level: "7", symbol: "", name: "Connaitre les pourcentages", grade: "CM2")
Skill.create!(domain: "Opérations", level: "1", symbol: "", name: "Poser et calculer une addition (deux nombres).", grade: "CM2")
Skill.create!(domain: "Opérations", level: "1", symbol: "", name: "Trouver le complément d’un nombre à un autre.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "1", symbol: "", name: "Utiliser la calculatrice pour trouver le résultat d’une opération.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "2", symbol: "", name: "Poser et calculer une addition (plusieurs nombres).", grade: "CM2")
Skill.create!(domain: "Opérations", level: "2", symbol: "", name: "Poser et calculer une soustraction (sans retenue).", grade: "CM2")
Skill.create!(domain: "Opérations", level: "2", symbol: "", name: "Compléter une table de Pythagore.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "2", symbol: "", name: "Connaitre les multiples d’un nombre.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "3", symbol: "", name: "Poser et calculer une soustraction (avec retenue).", grade: "CM2")
Skill.create!(domain: "Opérations", level: "3", symbol: "", name: "Multiplier par 10,100, 1 000.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "3", symbol: "", name: "Utiliser un répertoire pour multiplier.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "3", symbol: "", name: "Poser et calculer une multiplication (par un nombre à un chiffre)..", grade: "CM2")
Skill.create!(domain: "Opérations", level: "4", symbol: "", name: "Poser et calculer une multiplication (par un nombre à plusieurs chiffres).", grade: "CM2")
Skill.create!(domain: "Opérations", level: "4", symbol: "", name: "Calculer des quotients et des restes.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "4", symbol: "", name: "Utiliser toutes les touches « parenthèses » d’une calculatrice", grade: "CM2")
Skill.create!(domain: "Opérations", level: "5", symbol: "", name: "Poser et calculer une division par un diviseur à 1 chiffre .", grade: "CM2")
Skill.create!(domain: "Opérations", level: "5", symbol: "", name: "Poser et calculer une division par un diviseur à plusieurs chiffres", grade: "CM2")
Skill.create!(domain: "Opérations", level: "5", symbol: "", name: "Additionner des nombres décimaux.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "5", symbol: "", name: "Multiplier un nombre par 20, 50, 200 …", grade: "CM2")
Skill.create!(domain: "Opérations", level: "5", symbol: "", name: "Estimer l’ordre de grandeur d’un résultat (calcul approché).", grade: "CM2")
Skill.create!(domain: "Opérations", level: "5", symbol: "", name: "Utiliser les touches de mémoire de la calculatrice.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "6", symbol: "", name: "Soustraire des nombres décimaux.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "6", symbol: "", name: "Multiplier un nombre décimal par un nombre entier.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "6", symbol: "", name: "Utilise la touche . Sur la calculatrice.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "6", symbol: "", name: "Diviser un nombre entier par 10, 100, 1 000.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "6", symbol: "", name: "Multiplier ou diviser un nombre décimal par 10, 100...", grade: "CM2")
Skill.create!(domain: "Opérations", level: "7", symbol: "", name: "Calculer le quotient décimal d’une division posée.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "7", symbol: "", name: "Diviser un nombre décimal par un nombre entier.", grade: "CM2")
Skill.create!(domain: "Opérations", level: "7", symbol: "", name: "Multiplier un nombre décimal par un autre nombre décimal.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "1", symbol: "", name: "Résoudre des problèmes de transformation d’état sur des nombres jusqu’à 100 :  les billes, les pommes, le bus, les biscuits, l’argent de poche, le jeu de l’oie, les quilles.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "1", symbol: "", name: "Résoudre des problèmes de composition d’état sur des nombres jusqu’à 100 : les filles et garçons (les élèves), les poissons", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "1", symbol: "", name: "Résoudre des problèmes multiplicatifs avec un multiplicateur <= 5 : les paquets de bonbons", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "1", symbol: "", name: "Résoudre des problèmes de quotient et de partage simples:  les pirates, les équipes", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "2", symbol: "", name: "Exploiter les données d’un tableau, d’un diagramme : les températures", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "2", symbol: "", name: "Résoudre des problèmes de transformation d’état sur des nombres jusqu’à 600 :  les billes, les pommes, le bus, les biscuits, l’argent de poche, le jeu de l’oie, les quilles.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "2", symbol: "", name: "Résoudre des problèmes de composition d’état sur des nombres jusqu’à 600 : les filles et garçons (les élèves), les poissons", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "2", symbol: "", name: "Résoudre des problèmes multiplicatifs avec un multiplicateur <= 10 : les paquets de bonbons", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "2", symbol: "", name: "Résoudre des problèmes de quotient et de partage:  les pirates, les équipes", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "3", symbol: "", name: "Résoudre des problèmes de transformation et de composition d’état avec tous les nombres entiers.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "3", symbol: "", name: "Résoudre exposer clairement sa démarche dans des problèmes à étapes simples : la tour Eiffel", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "3", symbol: "", name: "Résoudre des problèmes multiplicatifs avec tous les nombres", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "3", symbol: "", name: "Résoudre des problèmes de quotient et de partage:  les rubans", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "4", symbol: "", name: "Exploiter les graphiques : ventes de gazette", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "4", symbol: "", name: "Résoudre des problèmes multiplicatifs : les images, les bagues", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "4", symbol: "", name: "Résoudre des problèmes de quotient et de partage:  les pépites.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "4", symbol: "", name: "Résoudre des problèmes de proportionnalité simples : avec 4 bandes", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "5", symbol: "", name: "Compléter un diagramme, un graphique.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "5", symbol: "", name: "Résoudre des problèmes de transformation et de composition d’état avec des nombres décimaux.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "5", symbol: "", name: "Résoudre des problèmes de quotient et de partage en utilisant la division posée.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "5", symbol: "", name: "Résoudre des problèmes de proportionnalité : le prix des cahiers", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "6", symbol: "", name: "Construite  un diagramme, un graphique.", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "6", symbol: "", name: "Résoudre des problèmes de proportionnalité : le plus illustré", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "7", symbol: "", name: "Résoudre des problèmes de proportionnalité : pourcentages", grade: "CM2")
Skill.create!(domain: "Résolution des Problèmes", level: "7", symbol: "", name: "Résoudre des problèmes de proportionnalité : échelles", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "1", symbol: "", name: "Etre capable d’écrire sur une ligne", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "1", symbol: "", name: "Savoir écrire lesminuscule en scripte et cursive, majuscules d’imprimerie avec modèle", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "2", symbol: "", name: "Tracer sans modèle les minuscules cursives et les majuscules d’imprimerie", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "2", symbol: "", name: "Recopier un texte de trois lignes sans erreur", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "2", symbol: "", name: "Copier une phrase avec traitement de texte", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "2", symbol: "", name: "Savoir présenter avec soin les travaux dans son cahier", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "2", symbol: "", name: "Remplir correctement une enveloppe", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "3", symbol: "", name: "Savoir tracer avec modèle les majuscules cursives (forme et taille)", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "3", symbol: "", name: "Recopier un texte de cinq lignes sans erreur", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "3", symbol: "", name: "Copier un texte avec dialogue avec traitement de texte", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "3", symbol: "", name: "Utiliser une feuille lignée pour guider l’écriture sur une feuille blanche", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "4", symbol: "", name: "Savoir tracer sans modèle certaines majuscules cursives (U V W Y O Q A N M)", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "4", symbol: "", name: "Copier des textes de PE avec traitement de texte", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "4", symbol: "", name: "Présenter systématiquement avec soin les travaux dans son cahier", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "4", symbol: "", name: "Poser des opérations", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "5", symbol: "", name: "Savoir tracer sans modèle certaines majuscules cursives (I J H K C G E T )", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "5", symbol: "", name: "Recopier un texte d’une dizaine de lignes sans erreur", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "5", symbol: "", name: "copier des textes de PE avec traitement de texte avec image", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "5", symbol: "", name: "Présenter avec soin une carte de géographie", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "6", symbol: "", name: "Savoir tracer sans modèle toutes les majuscules cursives s l d p r b f x z", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "6", symbol: "", name: "Recopier un texte d’une quinzaine de lignes sans erreur", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "6", symbol: "", name: "Tracer des graphiques", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "7", symbol: "", name: "Réaliser un croquis", grade: "CM2")
Skill.create!(domain: "Calligraphie", level: "7", symbol: "", name: "Prendre des notes", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "1", symbol: "", name: "Distinguer passé, présent et futur", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "1", symbol: "", name: "Reconnaitre le radical et la terminaison", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "1", symbol: "", name: "Reconnaitre la personne de conjugaison", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "1", symbol: "", name: "Conjuguer les verbes avoir et être au présent", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "2", symbol: "", name: "Trouver l’infinitif d’un verbe", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "2", symbol: "", name: "Conjuguer les verbes simples en -er au présent de l’indicatif", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "2", symbol: "", name: "Savoir conjuguer les verbes simples au futur", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "2", symbol: "", name: "Employer à bon escient présent et futur", grade: "CM2")
Skill.create!(domain: "Conjugaison", level: "3", symbol: "", name: "Savoir conjuguer les verbes au présent de l’indicatif", grade: "CM3")
Skill.create!(domain: "Conjugaison", level: "3", symbol: "", name: "Savoir conjuguer les verbes à l’imparfait", grade: "CM4")
Skill.create!(domain: "Conjugaison", level: "3", symbol: "", name: "Employer à bon escient les temps vus jusqu’à présent", grade: "CM5")
Skill.create!(domain: "Conjugaison", level: "4", symbol: "", name: "Savoir conjuguer au futur de l’indicatif", grade: "CM6")
Skill.create!(domain: "Conjugaison", level: "4", symbol: "", name: "Savoir conjuguer les verbes au passé composé", grade: "CM7")
Skill.create!(domain: "Conjugaison", level: "4", symbol: "", name: "Savoir distinguer les p. passés en é et les infinitifs en er", grade: "CM8")
Skill.create!(domain: "Conjugaison", level: "4", symbol: "", name: "Employer à bon escient les temps vus jusqu’à présent", grade: "CM9")
Skill.create!(domain: "Conjugaison", level: "5", symbol: "", name: "Savoir conjuguer les verbes au passé simple 3ème personne", grade: "CM10")
Skill.create!(domain: "Conjugaison", level: "5", symbol: "", name: "Employer à bon escient les temps vus jusqu’à présent", grade: "CM11")
Skill.create!(domain: "Conjugaison", level: "6", symbol: "", name: "Connaître les principes de formation des temps simples et composés", grade: "CM12")
Skill.create!(domain: "Conjugaison", level: "6", symbol: "", name: "Savoir conjuguer les verbes au plus-que-parfait de l’indicatif", grade: "CM13")
Skill.create!(domain: "Conjugaison", level: "6", symbol: "", name: "Savoir conjuguer les verbes au passé simple", grade: "CM14")
Skill.create!(domain: "Conjugaison", level: "6", symbol: "", name: "Employer à bon escient les temps vus jusqu’à présent", grade: "CM15")
Skill.create!(domain: "Conjugaison", level: "7", symbol: "", name: "Savoir conjuguer les verbes au présent de l’impératif", grade: "CM16")
Skill.create!(domain: "Conjugaison", level: "7", symbol: "", name: "Savoir conjuguer les verbes au présent du conditionnel", grade: "CM17")
Skill.create!(domain: "Conjugaison", level: "7", symbol: "", name: "Employer à bon escient les temps vus jusqu’à présent", grade: "CM18")
Skill.create!(domain: "Poésie et Expression orale", level: "1", symbol: "", name: "Etre capable de réciter de mémoire un poème", grade: "CM19")
Skill.create!(domain: "Poésie et Expression orale", level: "1", symbol: "", name: "Articuler avec soin et adapter la puissance de sa voix aux interlocuteurs", grade: "CM20")
Skill.create!(domain: "Poésie et Expression orale", level: "1", symbol: "", name: "Prendre la parole lorsque l’on n’a pas compris quelque chose", grade: "CM21")
Skill.create!(domain: "Poésie et Expression orale", level: "2", symbol: "", name: "Être capable de réciter de mémoire un poème ou un texte", grade: "CM22")
Skill.create!(domain: "Poésie et Expression orale", level: "2", symbol: "", name: "Reformuler une consigne", grade: "CM23")
Skill.create!(domain: "Poésie et Expression orale", level: "2", symbol: "", name: "Exposer à la classe ses hypothèses au cours d’une lecture", grade: "CM24")
Skill.create!(domain: "Poésie et Expression orale", level: "2", symbol: "", name: "Intervenir en classe pour donner son avis", grade: "CM25")
Skill.create!(domain: "Poésie et Expression orale", level: "2", symbol: "", name: "Intervenir lors d’une discussion en restant dans le sujet", grade: "CM26")
Skill.create!(domain: "Poésie et Expression orale", level: "2", symbol: "", name: "Tenir compte de ce qui a été dit (ne pas répéter ou faire répéter inutilement)", grade: "CM27")
Skill.create!(domain: "Poésie et Expression orale", level: "2", symbol: "", name: "Comprendre et exploiter un texte narratif écouté", grade: "CM28")
Skill.create!(domain: "Poésie et Expression orale", level: "3", symbol: "", name: "Être capable de réciter de mémoire un poème ou un texte", grade: "CM29")
Skill.create!(domain: "Poésie et Expression orale", level: "3", symbol: "", name: "Exposer à la classe ses procédures au cours d’une lecture", grade: "CM30")
Skill.create!(domain: "Poésie et Expression orale", level: "3", symbol: "", name: "Intervenir lors d’une discussion en restant dans le sujet", grade: "CM31")
Skill.create!(domain: "Poésie et Expression orale", level: "3", symbol: "", name: "Être capable de vouvoyer quelqu’un", grade: "CM32")
Skill.create!(domain: "Poésie et Expression orale", level: "3", symbol: "", name: "Présenter un livre à la classe", grade: "CM33")
Skill.create!(domain: "Poésie et Expression orale", level: "3", symbol: "", name: "Appliquer des consignes simples et complexes", grade: "CM34")
Skill.create!(domain: "Poésie et Expression orale", level: "4", symbol: "", name: "Être capable de réciter de mémoire un poème ou un texte", grade: "CM35")
Skill.create!(domain: "Poésie et Expression orale", level: "4", symbol: "", name: "Lire un livre dans une autre classe", grade: "CM36")
Skill.create!(domain: "Poésie et Expression orale", level: "4", symbol: "", name: "Adapter son niveau de langue aux situations rencontrées", grade: "CM37")
Skill.create!(domain: "Poésie et Expression orale", level: "4", symbol: "", name: "Distinguer lors d’un débat ce qui relève de la preuve ou d’un avis", grade: "CM38")
Skill.create!(domain: "Poésie et Expression orale", level: "4", symbol: "", name: "Reformuler les paroles d’un camarade", grade: "CM39")
Skill.create!(domain: "Poésie et Expression orale", level: "4", symbol: "", name: "Repérer, classer et utiliser des informations/", grade: "CM40")
Skill.create!(domain: "Poésie et Expression orale", level: "5", symbol: "", name: "Être capable de réciter de mémoire un poème ou un texte", grade: "CM41")
Skill.create!(domain: "Poésie et Expression orale", level: "5", symbol: "", name: "Présenter un exposé à la classe", grade: "CM42")
Skill.create!(domain: "Poésie et Expression orale", level: "5", symbol: "", name: "Etre capable d’argumenter", grade: "CM43")
Skill.create!(domain: "Poésie et Expression orale", level: "5", symbol: "", name: "Reformuler l’avis de quelqu’un", grade: "CM44")
Skill.create!(domain: "Poésie et Expression orale", level: "5", symbol: "", name: "Analyser et construire une argumentation", grade: "CM45")
Skill.create!(domain: "Poésie et Expression orale", level: "6", symbol: "", name: "Être capable de réciter de mémoire un poème ou un texte", grade: "CM46")
Skill.create!(domain: "Poésie et Expression orale", level: "6", symbol: "", name: "Proposer une lecture de dialogue dans une autre classe", grade: "CM47")
Skill.create!(domain: "Poésie et Expression orale", level: "6", symbol: "", name: "Expliquer à des camarades une règle de jeu", grade: "CM48")
Skill.create!(domain: "Poésie et Expression orale", level: "6", symbol: "", name: "Tél, obtenir les renseignements ou les résultats (résa, appel d’urgence, etc.)", grade: "CM49")
Skill.create!(domain: "Poésie et Expression orale", level: "7", symbol: "", name: "Être capable de réciter de mémoire un poème ou un texte", grade: "CM50")
Skill.create!(domain: "Poésie et Expression orale", level: "7", symbol: "", name: "Proposer une petite mise en scène de théatre", grade: "CM51")
Skill.create!(domain: "Poésie et Expression orale", level: "7", symbol: "", name: "Conceptualiser certaines notions (ne pas rester dans la simple illustration)", grade: "CM52")
Skill.create!(domain: "Poésie et Expression orale", level: "7", symbol: "", name: "Etre capable de mener un débat", grade: "CM53")
Skill.create!(domain: "Production d’écrit", level: "1", symbol: "", name: "J’écris quelque chose", grade: "CM54")
Skill.create!(domain: "Production d’écrit", level: "1", symbol: "", name: "Mon écriture est lisible", grade: "CM55")
Skill.create!(domain: "Production d’écrit", level: "1", symbol: "", name: "Je pense aux points et aux majuscules", grade: "CM56")
Skill.create!(domain: "Production d’écrit", level: "2", symbol: "", name: "J’écris des mots, des phrases qui parlent de ce qu’on m’a demandé", grade: "CM57")
Skill.create!(domain: "Production d’écrit", level: "2", symbol: "", name: "Mes phrases ont du sens", grade: "CM58")
Skill.create!(domain: "Production d’écrit", level: "2", symbol: "", name: "J’utilise le temps qu’on m’a demandé (passé, présent, futur)", grade: "CM59")
Skill.create!(domain: "Production d’écrit", level: "3", symbol: "", name: "J’utilise des pronoms pour ne pas répéter les sujets (il, elle, ils, elles, …)", grade: "CM60")
Skill.create!(domain: "Production d’écrit", level: "3", symbol: "", name: "Je pense aux pluriels des noms et des groupes nominaux", grade: "CM61")
Skill.create!(domain: "Production d’écrit", level: "3", symbol: "", name: "Je pense au pluriel des verbes", grade: "CM62")
Skill.create!(domain: "Production d’écrit", level: "3", symbol: "", name: "J’enrichis les groupes nominaux avec des adjectifs", grade: "CM63")
Skill.create!(domain: "Production d’écrit", level: "4", symbol: "", name: "Je sais utiliser des substituts autres que les pronoms", grade: "CM64")
Skill.create!(domain: "Production d’écrit", level: "4", symbol: "", name: "J’utilise des connecteurs temporels", grade: "CM65")
Skill.create!(domain: "Production d’écrit", level: "4", symbol: "", name: "J’utilise des connecteurs spatiaux", grade: "CM66")
Skill.create!(domain: "Production d’écrit", level: "4", symbol: "", name: "J’enrichis mon texte avec des compléments circonstanciels", grade: "CM67")
Skill.create!(domain: "Production d’écrit", level: "5", symbol: "", name: "J’utilise les temps à bon escient (concordance des temps)", grade: "CM68")
Skill.create!(domain: "Production d’écrit", level: "5", symbol: "", name: "J’utilise correctement les signes de ponctuation : virgule, point, point d’interrogation et d’exclamation", grade: "CM69")
Skill.create!(domain: "Production d’écrit", level: "5", symbol: "", name: "J’accorde correctement les verbes", grade: "CM70")
Skill.create!(domain: "Production d’écrit", level: "6", symbol: "", name: "J’ai organisé mon texte en paragraphes", grade: "CM71")
Skill.create!(domain: "Production d’écrit", level: "6", symbol: "", name: "J’utilise correctement les signes de ponctuation du dialogue", grade: "CM72")
Skill.create!(domain: "Production d’écrit", level: "6", symbol: "", name: "Je sais pronominaliser les compléments pour éviter les répétitions", grade: "CM73")
Skill.create!(domain: "Production d’écrit", level: "7", symbol: "", name: "J’enrichis mon texte suite aux conseils et propositions", grade: "CM74")
Skill.create!(domain: "Production d’écrit", level: "7", symbol: "", name: "J’utilise les outils d’aide pour corriger mon texte (dictionnaire, cahier de mots, fiche d’aide à la correction...)", grade: "CM75")
Skill.create!(domain: "Grammaire", level: "1", symbol: "", name: "Reconnaître la phrase", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "1", symbol: "", name: 'Connaître les signes de ponctuation fréquents (. , ! ? " " )', grade: "CM2")
Skill.create!(domain: "Grammaire", level: "1", symbol: "", name: "Distinguer les noms communs et les noms propres", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "1", symbol: "", name: "Connaître le genre des noms.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "1", symbol: "", name: "Connaitre singulier/pluriel", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "1", symbol: "", name: "Connaître les formes affirmative et négative", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Connaître les types de phrases", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Reconnaître le verbe", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Reconnaitre le déterminant", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Reconnaître le nom noyau dans un GN", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Connaître les pluriels particuliers : s, x, z -ou.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Connaître le féminin des noms.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Connaître la nature des mots (classer dans le cahier de mots).", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "2", symbol: "", name: "Savoir remplacer un nom par le bon pronom. (cas simple)", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Repérer le GN", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Connaître les adjectifs qualificatifs", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Accorder les adjectifs", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Connaître les pluriels particuliers : -eu, -eau, -au", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Retrouver le groupe verbal", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Retrouver le GS", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Repérer les différentes groupes dans la phrase.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Accorder le verbe à son sujet.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "3", symbol: "", name: "Savoir utiliser les signes de ponctuation ; : -", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Connaître les pluriels particuliers : -al", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Utiliser les prépositions", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Connaître le Complément du Nom", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Connaître les Complément de phrase.(CC)", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Préciser si le CC et de lieu, temps, manière...", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Connaitre les compléments du verbe.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Utiliser les pronoms compléments.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "4", symbol: "", name: "Savoir reconnaître et utiliser les adverbes", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Connaître les pluriels particuliers : -ail", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Connaitre les COI et COD", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Identifier l’attribut du Sujet", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Connaître la nature des mots (cas + complexes)", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Connaître les phrases simples, complexes et nominales", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Distinguer attribut et épithète", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Accorder participe passé avec être", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "5", symbol: "", name: "Accorder verbe avec sujet inversé", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "6", symbol: "", name: "Connaître et utiliser les pronoms personnels compléments", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "6", symbol: "", name: "Classer les déterminants", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "6", symbol: "", name: "Accorder le participe passé avec être et avoir.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "6", symbol: "", name: "Accorder le verbe avec le sujet qui", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Distinguer les principales, indépendantes et subordonnées.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Distinguer la nature et la fonction des mots", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Analyser grammaticalement des phrases variées", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Dans un texte, faire des inférences.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Dans un texte , retrouver des marques morphosyntaxiques.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Retrouver l’idée essentielle d’un texte.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Faire des hypothèses sur la suite d’un texte.", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "lire seul et présenter livre proposé par l’enseignant", grade: "CM2")
Skill.create!(domain: "Grammaire", level: "7", symbol: "", name: "Connaître les caractéristiques d’un genre littéraire", grade: "CM2")
Skill.create!(domain: "Lecture", level: "1", symbol: "", name: "Lire à haute voix un texte littéraire (M.Petit score > 85 ; Le Géant > 75 )", grade: "CM2")
Skill.create!(domain: "Lecture", level: "1", symbol: "", name: "Connaître le vocabulaire spécifique de la lecture :livre, couverture, page ...", grade: "CM2")
Skill.create!(domain: "Lecture", level: "1", symbol: "", name: "Compléter un texte à trous simple en choisissant parmi des mots donnés.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "2", symbol: "", name: "Lire à haute voix un texte littéraire (M.Petit score >100; Le Géant >90)", grade: "CM2")
Skill.create!(domain: "Lecture", level: "2", symbol: "", name: "Dans un texte lu par l’enseignant, retrouver des substituts.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "2", symbol: "", name: "Dans un texte lu par l’enseignant, faire des inférences.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "2", symbol: "", name: "Dans un texte , retrouver des marques morphosyntaxiques.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "2", symbol: "", name: "Retrouver l’idée essentielle d’un texte lu par l’enseignant.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "2", symbol: "", name: "Faire des hypothèses sur la suite d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "2", symbol: "", name: "Connaître les caractéristiques des genres littéraires et ses archétypes.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Lire à haute voix un texte littéraire (M.Petit score > 116; Le Géant >99", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Dans un texte, retrouver des substituts.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Dans un texte, faire des inférences.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Dans un texte , retrouver des marques morphosyntaxiques.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Retrouver l’idée essentielle d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Faire des hypothèses sur la suite d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Lire seul un livre, le présenter dans son carnet de voyage dans les arts.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Être capable d’emprunter un ouvrage en BCD", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Pour un texte, citer sa source, sa nature, sa fonction.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "3", symbol: "", name: "Connaître les caractéristiques d’un genre littéraire", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Lire à haute voix un texte littéraire(M.Petit score > 127 ; Le Géant > 103)", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Dans un texte, retrouver des substituts.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Dans un texte, faire des inférences.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Dans un texte , retrouver des marques morphosyntaxiques.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Retrouver l’idée essentielle d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Faire des hypothèses sur la suite d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Lire seul un livre, présenter à la classe", grade: "CM2")
Skill.create!(domain: "Lecture", level: "4", symbol: "", name: "Connaître les caractéristiques d’un genre littéraire", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Proposer une lecture à voix haute d’un texte dans une autre classe", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Lire à haute voix un texte littéraire. (M.Petit score >132 ; Le Géant >104)", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Dans un texte, retrouver des substituts.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Dans un texte, faire des inférences.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Dans un texte , retrouver des marques morphosyntaxiques.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Retrouver l’idée essentielle d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Faire des hypothèses sur la suite d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Savoir se repérer à la bibliothèque municipale .", grade: "CM2")
Skill.create!(domain: "Lecture", level: "5", symbol: "", name: "Connaître les caractéristiques d’un genre littéraire", grade: "CM2")
Skill.create!(domain: "Lecture", level: "6", symbol: "", name: "Lire à haute voix un texte littéraire. (M.Petit score >136 ; Le Géant >130)", grade: "CM2")
Skill.create!(domain: "Lecture", level: "6", symbol: "", name: "Dans un texte, retrouver des substituts.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "6", symbol: "", name: "Dans un texte, faire des inférences.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "6", symbol: "", name: "Dans un texte , retrouver des marques morphosyntaxiques.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "6", symbol: "", name: "Retrouver l’idée essentielle d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "6", symbol: "", name: "Faire des hypothèses sur la suite d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "6", symbol: "", name: "Connaître les caractéristiques d’un genre littéraire", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "Lire en temps imparti une liste de mots. (M.Petit score > 146 ; Le Géant > 140", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "Dans un texte, retrouver des substituts.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "Dans un texte, faire des inférences.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "Dans un texte , retrouver des marques morphosyntaxiques.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "Retrouver l’idée essentielle d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "Faire des hypothèses sur la suite d’un texte.", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "lire seul et présenter livre proposé par l’enseignant", grade: "CM2")
Skill.create!(domain: "Lecture", level: "7", symbol: "", name: "Connaître les caractéristiques d’un genre littéraire", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "1", symbol: "", name: "Ecrire correctement les mots de la liste 85 %", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "1", symbol: "", name: "Distinguer a/à", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "1", symbol: "", name: "Lire et écrire correctement le son [S] (s/ss, c/ç)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "1", symbol: "", name: "Connaître l’alphabet et l’ordre alphabétique", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "1", symbol: "", name: "Dire si un mot se trouve plutôt au début, au milieu ou à la fin d’un dictionnaire", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "1", symbol: "", name: "Construire ou compléter des familles de mots", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "1", symbol: "", name: "Connaître les contraires", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Ecrire correctement les mots de la liste", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Distinguer et/est", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Connaitre les accents", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Utiliser correctement la lettre G", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Placer M devant m,b et p", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Savoir classer dans l’ordre alphabétique (2 lettres identiques)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Trouver un mot dans le dictionnaire", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "2", symbol: "", name: "Connaître les synonymes", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "3", symbol: "", name: "Ecrire correctement les mots de la liste", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "3", symbol: "", name: "Distinguer on/ont", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "3", symbol: "", name: "Savoir classer dans l’ordre alphabétique (début identique)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "3", symbol: "", name: "Trouver un mot dans le dictionnaire en temps limité (moins d’une minute)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "3", symbol: "", name: "Connaître les homonymes", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "3", symbol: "", name: "Distinguer les termes génériques et les termes particuliers", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "4", symbol: "", name: "Ecrire correctement les mots de la liste", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "4", symbol: "", name: "Distinguer son/sont", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "4", symbol: "", name: "Trouver un mot dans le dictionnaire en temps limité (45 secondes)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "4", symbol: "", name: "Comprendre un article de dictionnaire", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "4", symbol: "", name: "Connaître les différents sens d’un mot, distinguer selon le sens du contexte", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "4", symbol: "", name: "Regrouper des mots selon le sens de leur préfixe", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "4", symbol: "", name: "Regroupe des mots selon le sens de leur suffixe", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "5", symbol: "", name: "Ecrire correctement les mots de la liste", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "5", symbol: "", name: "Distinguer ou/où", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "5", symbol: "", name: "Distinguer ses/ces/c’est/s’est", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "5", symbol: "", name: "Distinguer ce/se, c’/s’", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "5", symbol: "", name: "Trouver un mot dans le dictionnaire en temps limité (30 secondes)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "5", symbol: "", name: "Distinguer le sens propre et le sens figuré d’un mot", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "5", symbol: "", name: "Connaître les niveaux de langue", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Ecrire correctement les mots de la liste", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Distinguer leur/leurs", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Distinguer on / on n’", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Distinguer la / là/l’a", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Trouver un mot dans le dictionnaire en temps limité (25 secondes)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Dans un texte, relever les mots relevant d’un même champ lexical.", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Pour un mot fournir un ou plus mots de la famille en vérifier l’existence", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Regrouper des mots selon le sens de leur préfixe et connaître ce sens", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "6", symbol: "", name: "Regrouper des mots selon le sens de leur sufixe et connaître ce sens", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "7", symbol: "", name: "Ecrire correctement les mots de la liste 90 % d’un liste niveau 3", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "7", symbol: "", name: "Utiliser la construction d’un mot inconnu pour le comprendre", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "7", symbol: "", name: "Classer en repérant les variations d’intensité (ex. bon, délicieux, succulent)", grade: "CM2")
Skill.create!(domain: "Vocabulaire", level: "7", symbol: "", name: "Utilser les bases grecques et latines pour construire des mots.", grade: "CM2")
