User.create!(email: "bensouc@gmail.com", password: "secret", first_name: "toto", last_name: "titi")

puts "Destroy all CE2 skills"
s= Skill.where(grade: "CE2")
c = s.count
wp = WorkPlan.where(grade: "CE2" )
wp.each(&:destroy)
s.each {|skill|
  chals = Challenge.where(skill: skill)
  chals.each(&:destroy)
  skill.destroy
}

puts "#{c} skills ont été détruites"

puts "creating all the Skills"
Skill.create!(domain: 'Conjugaison', level: '1', symbol:'◼', name:'Reconnaître passé, présent et futur', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '1', symbol:'⬥', name:'Trouver l’infinitif d’un verbe', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '1', symbol:'▲', name:'Reconnaître le radical et la terminaison d’un verbe', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '2', symbol:'◼', name:'Conjuguer les verbes du 1re groupe au présent', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '2', symbol:'⬥', name:'Conjuguer les verbes être et avoir au présent', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '2', symbol:'▲', name:'Conjuguer les verbes faire, dire, aller, venir, pouvoir, voir, vouloir et prendre au présent', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '3', symbol:'◼', name:'Conjuguer les verbes du 1re groupe à l’imparfait', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '3', symbol:'⬥', name:'Conjuguer les verbes être et avoir à l’imparfait', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '3', symbol:'▲', name:'Conjuguer les verbes faire, dire, aller, venir, pouvoir, voir, vouloir et prendre à l’imparfait', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '4', symbol:'◼', name:'Conjuguer les verbes du premier groupe au passé composé', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '4', symbol:'⬥', name:'Conjuguer les verbes être et avoir au passé composé', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '4', symbol:'▲', name:'Conjuguer les verbes faire, dire, aller, venir, pouvoir, voir, vouloir et prendre au passé composé', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '5', symbol:'◼', name:'Conjuguer les verbes du 1re groupe au futur', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '5', symbol:'⬥', name:'Conjuguer les verbes être et avoir au futur', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '5', symbol:'▲', name:'Conjuguer les verbes faire, dire, aller, venir, pouvoir, voir, vouloir et prendre au futur', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '6', symbol:'◼', name:'Savoir distinguer les participes passés en -é et l’infinitif en -er', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '6', symbol:'⬥', name:'Distinguer temps simples et temps composés', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '6', symbol:'▲', name:'Identifier les 3 groupes de verbes', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '7', symbol:'◼', name:'Savoir conjuguer tous les verbes au présent', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '7', symbol:'⬥', name:'Savoir conjuguer tous les verbes à l’imparfait', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '7', symbol:'▲', name:'Savoir conjuguer tous les verbes au futur', grade: 'CE2')
Skill.create!(domain: 'Conjugaison', level: '7', symbol:'🞮', name:'Savoir conjuguer les verbes au passé composé', grade: 'CE2')


Skill.create!(domain: 'Vocabulaire', level: '1', symbol:'◼', name:'Classer les lettres dans l’ordre alphabétique', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '1', symbol:'⬥', name:'Classer des mots par catégories', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '1', symbol:'▲', name:'Trouver le mot étiquette.', grade: 'CE2')

Skill.create!(domain: 'Vocabulaire', level: '2', symbol:'◼', name:'Classer des mots d’après la première lettre', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '2', symbol:'⬥', name:'Identifier des familles de mots', grade: 'CE2')

Skill.create!(domain: 'Vocabulaire', level: '3', symbol:'◼', name:'Classer des mots dans l’ordre alphabétique (2 lettres identiques)', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '3', symbol:'⬥', name:'Reconnaître et trouver des contraires', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '3', symbol:'▲', name:'Trouver un mot repère dans le dictionnaire', grade: 'CE2')

Skill.create!(domain: 'Vocabulaire', level: '4', symbol:'◼', name:'Classer des mots dans l’ordre alphabétique (début identique)', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '4', symbol:'⬥', name:'Reconnaître et trouver des synonymes', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '4', symbol:'▲', name:'Comprendre un article de dictionnaire : retrouver le mot défini et différencier la définition de l’exemple', grade: 'CE2')

Skill.create!(domain: 'Vocabulaire', level: '5', symbol:'◼', name:'Trouver un mot dans le dictionnaire', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '5', symbol:'⬥', name:'Comprendre un article de dictionnaire : savoir donner la classe grammaticale, un synonyme et un antonyme du mot recherché', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '5', symbol:'▲', name:'Choisir la bonne définition pour un mot à plusieurs sens', grade: 'CE2')

Skill.create!(domain: 'Vocabulaire', level: '6', symbol:'◼', name:'Trouver un mot dans un dictionnaire dans un temps limité (2 min)', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '6', symbol:'⬥', name:'Regrouper des mots selon le sens de leur préfixe et de leur suffixe', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '6', symbol:'▲', name:'Identifier les niveaux de langue', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '6', symbol:'🞮', name:'Trouver l’orthographe d’un mot à l’aide d’un outil (répertoire, dictionnaire, etc.)', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '7', symbol:'◼', name:'Connaître quelques homonymes', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '7', symbol:'⬥', name:'Faire la différence entre sens propre et sens figuré', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '7', symbol:'▲', name:'Dans un texte, à l’oral, relever les mots relevant d’un même champ lexical', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '7', symbol:'🞮', name:'Pour un mot, fournir un ou plusieurs mots de la famille, en vérifier l’orthographe', grade: 'CE2')
Skill.create!(domain: 'Vocabulaire', level: '7', symbol:'⬟', name:'Regrouper des mots selon le sens de leur préfixe ou de leur suffixe et connaître ce sens', grade: 'CE2')



Skill.create!(domain: 'Orthographe', level: '1', symbol:'◼', name:'Écrire sans erreur de manière autonome des mots simples en respectant les correspondances entre lettres et sons', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '2', symbol:'⬥', name:'Savoir qu’il faut mettre un M devant m, b, p', grade: 'CE2')


Skill.create!(domain: 'Orthographe', level: '3', symbol:'⬥', name:'Connaitre les valeurs de la lettre «g»', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '3', symbol:'▲', name:'Distinguer «et» «es» «est »', grade: 'CE2')

Skill.create!(domain: 'Orthographe', level: '4', symbol:'⬥', name:'Connaître les valeurs de la lettre « S »', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '4', symbol:'▲', name:'Connaitre les valeurs de la lettre « C »', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '4', symbol:'🞮', name:'Distinguer « a/à »', grade: 'CE2')

Skill.create!(domain: 'Orthographe', level: '5', symbol:'⬥', name:'Distinguer ou/où ', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '5', symbol:'▲', name:'Distinguer son/sa/ses', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '5', symbol:'🞮', name:'Distinguer son/sont', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '5', symbol:'⬟', name:'Mettre au pluriel les noms (cas du -s au pluriel)  ', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '5', symbol:'♥', name:'Mettre au pluriel les noms en -al', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '5', symbol:'⬤', name:'Mettre au pluriel que les noms en -s, -x, -z', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '5', symbol:'♣', name:'Mettre au pluriel les noms en –ou', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '6', symbol:'⬥', name:'Mettre au féminin les noms', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '6', symbol:'▲', name:'Mettre au pluriel les adjectifs', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '6', symbol:'🞮', name:'Mettre au féminin les adjectifs', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '6', symbol:'⬟', name:' Ecrire correctement les noms et adjectifs qui se terminent par une lettre muette', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '7', symbol:'⬥', name:'Ecrire correctement -é ou -er à la fin d’un verbe', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '7', symbol:'▲', name:'Distinguer ses/ces/c’est/s’est ; ce/se, c’/s’', grade: 'CE2')
Skill.create!(domain: 'Orthographe', level: '7', symbol:'🞮', name:'Savoir marquer tous les accords dans le groupe nominal (féminin et pluriel)', grade: 'CE2')

Skill.create!(domain: 'Grammaire', level: '1', symbol:'◼', name:'Reconnaître une phrase et différencier phrase/ligne', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '1', symbol:'⬥', name:'Mettre des mots dans l’ordre pour former une phrase', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '1', symbol:'▲', name:'Reconnaitre le verbe dans une phrase', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '1', symbol:'🞮', name:'Savoir remplacer un groupe nominal par un pronom personnel', grade: 'CE2')

Skill.create!(domain: 'Grammaire', level: '2', symbol:'◼', name:'Trouver le sujet du verbe lorsque c’est un pronom personnel', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '2', symbol:'⬥', name:'Dans un groupe nominal, reconnaître et distinguer le nom (propre et commun) et le déterminant (article)', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '2', symbol:'▲', name:'Distinguer les noms propres et les noms communs', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '2', symbol:'🞮', name:'Donner le genre (masculin/féminin) d’un nom', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '2', symbol:'⬟', name:'Donner le nombre (singulier/pluriel) d’un nom', grade: 'CE2')

Skill.create!(domain: 'Grammaire', level: '3', symbol:'◼', name:'Trouver le sujet du verbe lorsque c’est un groupe nominal', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '3', symbol:'⬥', name:'Dans un groupe nominal, reconnaître et distinguer le nom (propre et commun) et le déterminant (article)', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '3', symbol:'▲', name:'Identifier le genre d’un groupe nominal', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '3', symbol:'🞮', name:'Identifier le nombre d’un groupe nominal', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '3', symbol:'⬟', name:'Reconnaître les principaux constituants de la phrase : les compléments', grade: 'CE2')

Skill.create!(domain: 'Grammaire', level: '4', symbol:'◼', name:'Identifier la nature du sujet (nom, GN, PP)', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '4', symbol:'⬥', name:'Reconnaître un adjectif qualificatif, un verbe, un déterminant, un nom, un pronom personnel dans une phrase.', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '4', symbol:'▲', name:'Identifier les pronoms et dire ce qu’ils désignent', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '4', symbol:'🞮', name:'Reconnaître et distinguer dans un texte : les phrases déclaratives et les phrases interrogatives', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '4', symbol:'⬟', name:'Reconnaître et distinguer dans un texte : les formes négatives et les formes exclamatives ', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '4', symbol:'♥', name:'Savoir accorder le verbe avec son sujet (pronom personnel et groupe nominal simple)', grade: 'CE2')

Skill.create!(domain: 'Grammaire', level: '5', symbol:'◼', name:'Trouver le sujet dans une phrase et ce qu’on en dit', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '5', symbol:'⬥', name:'Reconnaître un nom (propre et commun), un déterminant, un pronom personnel, un adjectif, un verbe dans un texte', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '5', symbol:'🞮', name:'Marquer les accords en genre dans le groupe nominal', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '5', symbol:'🞮', name:'Marquer les accords en nombre dans le groupe nominal', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '5', symbol:'⬟', name:'Transformer des phrases de différents types et formes : affirmatives/négatives (encore, jamais, toujours, ni…ni, etc.) et déclaratives/interrogatives', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '6', symbol:'◼', name:'Identifier le/les groupes nominaux dans une phrase', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '6', symbol:'⬥', name:'Reconnaître les principaux constituants de la phrase : le sujet (de qui on parle), ce qu’on en dit, les compléments', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '6', symbol:'▲', name:'Appliquer les règles simples d’accord dans la phrase (transposition).', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '6', symbol:'🞮', name:'Distinguer l’article défini de l’article indéfini', grade: 'CE2')

Skill.create!(domain: 'Grammaire', level: '7', symbol:'◼', name:'Reconnaître et identifier le complément du nom dans un groupe nominal', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '7', symbol:'⬥', name:'Savoir accorder le verbe avec son sujet (accord avec le nom noyau)', grade: 'CE2')
Skill.create!(domain: 'Grammaire', level: '7', symbol:'▲', name:'Reconnaître et distinguer tout type de phrases dans un texte (déclaratives, interrogatives, impératives)', grade: 'CE2')





Skill.create!(domain: 'Géométrie', level: '1', symbol:'◼', name:'1 - Reproduire une figure sur un quadrillage', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'◼', name:'2 - Suivre un itinéraire tracé sur un plan', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'◼', name:'3 - Représenter un itinéraire effectué sur un plan (village/quartier)', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'◼', name:'4 - Réaliser des déplacements sur un logiciel adapté', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'◼', name:'5 - Comprendre et produire un algorithme simple', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬟', name:'1- Utiliser le compas pour tracer un cercle', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬟', name:'2 - Utiliser le compas pour tracer un cercle en connaissant centre/point/rayon/diamètre', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬟', name:'3 - Utiliser l’équerre pour vérifier un angle droit', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬟', name:'4 - Utiliser l’équerre pour tracer un angle droit', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬟', name:'5 - Reporter une longueur avec le compas sur une droite déjà tracée', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬟', name:'6 - Utiliser une règle graduée, une équerre et un compas pour tracer les figures usuelles', grade: 'CE2')

Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'1 - Reconnaître les figures : carré, rectangle,cercle, triangle', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'2 - Connaître le vocabulaire des figures géométriques : polygone, côté, sommet', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'3 - Connaître le vocabulaire des figures géométriques : droite, segment, milieu, angle droit', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'4 - Identifier, compléter un carré et marquer les angles droits', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'5 - Identifier, compléter un rectangle et marquer les angles droits', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'6 - Connaître le vocabulaire des figures géométriques : cercle, disque, rayon, centre', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'7 - Construire un cercle avec un compas, en connaissant centre/rayon/diamètre', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'8 - Nommer et décrire : un carré/un rectangle/un triangle', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'9 - Reproduire :un carré/un rectangle/un triangle/des assemblages de ces figures sur tout support', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'⬥', name:'10 - Trouver le milieu d’un segment en utilisant la règle graduée', grade: 'CE2')

Skill.create!(domain: 'Géométrie', level: '1', symbol:'🞮', name:'1 - Reconnaître si une figure a un axe de symétrie avec du papier calque, des découpages ou des pliages', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'🞮', name:'2 - Repérer le ou les axes de symétrie d’une figure', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'🞮', name:'3 - Tracer la figure symétrique d’une autre par rapport à un axe sur une feuille quadrillée ou pointée', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'▲', name:'1 - Reconnaître et nommer les solides: cube / boule / cône / pyramide / cylindre / pavé droit', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'▲', name:'2 - Décrire des solides avec le bon vocabulaire : face, sommet et arête', grade: 'CE2')
Skill.create!(domain: 'Géométrie', level: '1', symbol:'▲', name:'3 - Construire le patron d’un cube', grade: 'CE2')


Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'1 - Mesurer des segments avec la règle (en cm)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'2 - Mesurer des segments en cm et mm', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'3 - Mesures des lignes brisées en cm et en mm', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'4 - Connaître les relations entre les différentes unités de longueur : mm, cm, dm, m', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'5 - Connaître les relations entre les différentes unités de longueur : m et km', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'6 - Reproduire des segments en dm, cm et/ou mm en utilisant une règle graduée', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'7 - Mesurer des longueurs avec le mètre ruban', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'8 - Estimer un ordre de grandeur des objets du quotidien (mm, cm, m, km)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'9 - Utiliser le lexique spécifique associé aux longueurs (plus long, court, près, loin, double, moitié, règle graduée, mm, cm, dm, m, km)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'◼', name:'10 - Résoudre des problèmes de mesure de longueurs', grade: 'CE2')

Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'1 - Choisir l’unité de masse correspondant le mieux pour exprimer une masse (g, kg, t)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'2 - Estimer un ordre de grandeur des objets du quotidien (g, kg)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'3 - Peser des objets (g, kg)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'4 - Connaître les relations entre t, kg et g', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'5 - Résoudre des problèmes impliquant des masses', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'6 - Comparer des objets selon leur contenance, en transvasant', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'7 - Mesurer des contenances (cL,dL, L)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'8 - Connaître les relations entre L,dL et cL', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'⬥', name:'9 - Résoudre des problèmes impliquant des contenances', grade: 'CE2')

Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'1 - Connaître et utiliser la monnaie (en euro) : donner une somme d’argent, calculer une somme, rendre la monnaie', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'2 - Connaître et utiliser la monnaie (+centimes) : donner une somme d’argent, calculer une somme, rendre la monnaie', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'3 - Connaître la relation entre centimes d’euro et euro', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'4 - Utiliser le lexique spécifique associé aux prix (plus cher, moins cher, rendre la monnaie, billet, pièce, somme, euros, centimes d’euros)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'5 - Résoudre des problèmes avec de la monnaie', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'1 - Lire l’heure (heure pile)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'2 - Lire l’heure (pile et demie)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'3 - Lire l’heure (pile, demie, quart, moins quart)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'4 - Lire l’heure', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'5 - Connaître les relations entre mesures du temps (1 semaine =7 jours; 1 mois =29,30 ou 31 jours, 1 année = 365j ; 1 année =12 mois)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'6 - Connaître les relations entre mesures du temps (année/siècle/millénaire, jour/heure, heure/minute, minute/seconde)', grade: 'CE2')
Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'7 - Utiliser le lexique spécifique associé aux durées (plus long, court, avant, après, plus tôt, plus tard, horloge, montre, aiguille, millénaire, siècle, année, jour, semaine, mois, heure, minute, seconde)', grade: 'CE2')

Skill.create!(domain: 'Grandeurs et Mesures', level: '1', symbol:'▲', name:'8 - Résoudre des problèmes de durée (heure et minute)', grade: 'CE2')

Skill.create!(domain: 'Numération', level: '1', symbol:'◼', name:'Connaître les nombres (écrire/nommer) jusqu’à 60', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '1', symbol:'⬥', name:'Comparer, ranger et encadrer les nombres jusqu’à 60', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '1', symbol:'▲', name:'Ecrire des suites de nombres jusqu’à 60', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '1', symbol:'🞮', name:'Décomposer et représenter une quantité jusqu’à 60', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '1', symbol:'⬟', name:'Repérer et placer les nombres jusqu’à 60 sur une droite graduée', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '2', symbol:'◼', name:'Connaître les nombres (écrire/nommer) jusqu’à 100', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '2', symbol:'⬥', name:'Comparer, ranger et encadrer les nombres jusqu’à 100', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '2', symbol:'▲', name:'Ecrire des suites de nombres jusqu’à 100', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '2', symbol:'🞮', name:'Décomposer et représenter une quantité jusqu’à 100', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '2', symbol:'⬟', name:'Repérer et placer les nombres jusqu’à 100 sur une droite graduée', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '3', symbol:'◼', name:'Connaître les nombres (écrire/nommer) jusqu’à 600', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '3', symbol:'⬥', name:'Comparer, ranger et encadrer les nombres jusqu’à 600', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '3', symbol:'▲', name:'Ecrire des suites de nombres jusqu’à 600', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '3', symbol:'🞮', name:'Décomposer et représenter une quantité jusqu’à 600', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '3', symbol:'⬟', name:'Repérer et placer les nombres jusqu’à 600 sur une droite graduée', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '3', symbol:'♥', name:'Connaitre les nombres pairs et impairs', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '4', symbol:'◼', name:'Connaître les nombres (écrire/nommer) jusqu’à 1 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '4', symbol:'⬥', name:'Comparer, ranger et encadrer les nombres jusqu’à 1 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '4', symbol:'▲', name:'Ecrire des suites de nombres jusqu’à 1 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '4', symbol:'🞮', name:'Décomposer et représenter une quantité jusqu’à 1 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '4', symbol:'⬟', name:'Repérer et placer les nombres jusqu’à 1 000 sur une droite graduée', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '4', symbol:'♥', name:'Connaitre les nombres romains jusqu’à X', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '5', symbol:'◼', name:'Connaître les nombres (écrire/nommer) jusqu’à 10 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '5', symbol:'⬥', name:'Comparer, ranger et encadrer les nombres jusqu’à 10 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '5', symbol:'▲', name:'Ecrire des suites de nombres jusqu’à 10 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '5', symbol:'🞮', name:'Décomposer et représenter une quantité jusqu’à 10 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '5', symbol:'⬟', name:'Repérer et placer les nombres jusqu’à 10 000 sur une droite graduée', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '5', symbol:'♥', name:'Connaitre les nombres romains jusqu’à XX', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '6', symbol:'◼', name:'Connaître les nombres (écrire/nommer) jusqu’à 100 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '6', symbol:'⬥', name:'Comparer, ranger et encadrer les nombres jusqu’à 100 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '6', symbol:'▲', name:'Ecrire des suites de nombres jusqu’à 100 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '6', symbol:'🞮', name:'Décomposer et représenter une quantité jusqu’à 100 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '6', symbol:'⬟', name:'Repérer et placer les nombres jusqu’à 100 000 sur une droite graduée', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '6', symbol:'♥', name:'Connaitre les nombres romains jusqu’à L', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '7', symbol:'◼', name:'Connaître les nombres (écrire/nommer) jusqu’à 1 000 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '7', symbol:'⬥', name:'Comparer, ranger et encadrer les nombres jusqu’à 1 000 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '7', symbol:'▲', name:'Ecrire des suites de nombres jusqu’à 1 000 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '7', symbol:'🞮', name:'Décomposer et représenter une quantité jusqu’à 1 000 000', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '7', symbol:'⬟', name:'Repérer et placer les nombres jusqu’à 1 000 000 sur une droite graduée.', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '7', symbol:'♥', name:'Utiliser des fractions pour mesurer des longueurs', grade: 'CE2')
Skill.create!(domain: 'Numération', level: '7', symbol:'♣', name:'Construire une surface dont l’aire est donnée par une fraction', grade: 'CE2')

Skill.create!(domain: 'Calcul', level: '1', symbol:'◼', name:'Mémoriser les tables d’addition 10', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '1', symbol:'⬥', name:'Additionner des dizaines entières', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '1', symbol:'▲', name:'Connaître les compléments à 10', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '1', symbol:'🞮', name:'Poser et résoudre une addition simple (sans retenue)', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '1', symbol:'⬟', name:'Poser et résoudre une soustraction simple (sans retenue)', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '2', symbol:'◼', name:'Connaître les tables de multiplication de 2, 5 et 10', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '2', symbol:'⬥', name:'Connaître les doubles et les moitiés des nombres <10', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '2', symbol:'▲', name:'Ajouter et retirer 9 et 11', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '2', symbol:'🞮', name:'Écrire des nombres dictés jusqu’à 100', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '2', symbol:'⬟', name:'Poser et résoudre une addition avec retenue', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '3', symbol:'◼', name:'Connaître les tables de multiplication jusqu’à 5', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '3', symbol:'⬥', name:'Connaître les doubles et les moitiés des nombres <20', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '3', symbol:'▲', name:'Réaliser des additions sur les 100 premiers nombres', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '3', symbol:'🞮', name:'Connaître le complément à 100 d’un nombre.', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '3', symbol:'⬟', name:'Multiplier un nombre par 10 et 100', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '3', symbol:'♥', name:'Poser et résoudre une soustraction avec retenue', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '3', symbol:'♣', name:'Poser et résoudre une addition de plusieurs nombres (nbs à 3 chiffres)', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '4', symbol:'◼', name:'Connaître les tables de multiplication jusqu’à 10', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '4', symbol:'⬥', name:'Connaître les doubles et moitiés les plus courants', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '4', symbol:'▲', name:'Multiplier un nombre par 10 et 100', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '4', symbol:'🞮', name:'Réaliser des soustractions sur les 100 premiers nombres', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '4', symbol:'⬟', name:'Calculer le quotient et le reste d’une division par un nombre à 1 chiffre', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '4', symbol:'♥', name:'Écrire des nombres dictés jusqu’à 1 000', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '4', symbol:'♣', name:'Poser et résoudre une multiplication par un nombre à 1 chiffre', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '5', symbol:'◼', name:'Multiplier un nombre par 20, 200 …', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '5', symbol:'⬥', name:'Ajouter et retirer 11', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '5', symbol:'▲', name:'Connaître les compléments à 1 000', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '5', symbol:'🞮', name:'Estimer des sommes, des différences', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '5', symbol:'⬟', name:'Calculer le quotient et le reste d’une division par 10, 25, 50 et 100', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '5', symbol:'♥', name:'Écrire des nombres dictés jusqu’à 10 000', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '5', symbol:'♣', name:'Poser et résoudre une multiplication par un nombre à 2 chiffres', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '6', symbol:'◼', name:'Encadrer un nombre entier à la dizaine, à la centaine...', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '6', symbol:'⬥', name:'Connaître les doubles et moitiés des nombres jusqu’à 200', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '6', symbol:'▲', name:'Écrire des nombres dictés jusqu’à 100 000', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '6', symbol:'🞮', name:'Ajouter et retirer 19 et 21', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '7', symbol:'◼', name:'Ajouter et retirer 99 et 101', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '7', symbol:'⬥', name:'Connaître les doubles et moitiés des nombres jusqu’à 500', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '7', symbol:'▲', name:'Écrire des nombres dictés jusqu’à 1 000 000', grade: 'CE2')
Skill.create!(domain: 'Calcul', level: '7', symbol:'🞮', name:'Poser et résoudre une multiplication par un nombre à plusieurs chiffres', grade: 'CE2')
